package javaFB.com.google.flatbuffers;// automatically generated by the FlatBuffers compiler, do not modify

public final class Gender {
  private Gender() { }
  public static final byte Female = 0;
  public static final byte Male = 1;

  public static final String[] names = { "Female", "Male", };

  public static String name(int e) { return names[e]; }
}

